### ISSUE TITLE
Move underlying leopard fork to lazyledger org and update submodule link

### ISSUE THREAD

**Issue by musalbas** [lazyledger/go-leopard#4]
Also: should recover_parity_chunks_too be merged with master branch?

**Comment by liamsi** [comment]
Good point, I just transferred ownership: https://github.com/lazyledger/leopard 
Will update the submodule connection in go-leopard and merge the branch we used to master (if that isn't already the case).

**Comment by liamsi** [comment]
This merges `recover_parity_chunks_too` to master (and cleans the branch from some accidentally checked-in artefacts): https://github.com/lazyledger/leopard/pull/1

**Comment by liamsi** [comment]
done in: https://github.com/lazyledger/go-leopard/commit/9e336c1ce29a06cacb5b92d513d39b6aacfd74f7
